plugins {
    id 'fabric-loom' version '1.1-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

extra {
    apply plugin: 'fabric-loom'
    loom {
        minecraftVersion = '1.20.1'
        mappings = '1.20.1+build.1'
        accessWidener = 'src/main/resources/accessWidener.txt'
        modId = 'dinosaurdimensionmod'
        version = '1.0.0'
        javaVersion = JavaVersion.VERSION_17
    }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.20.1'
    mappings 'net.fabricmc:yarn:1.20.1+build.1:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.14.21'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.84.0+1.20.1'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', project.minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'fabric.mod.json'
        include 'assets/**'
        include 'data/**'
        expand(project.properties)
    }
    into "build/resources/main"
}
